
CREATE TABLE public.tmp_registry
(
    region text COLLATE pg_catalog."default",
    last_year integer,
    data_source text COLLATE pg_catalog."default",
    first_year integer,
    organization text COLLATE pg_catalog."default",
    lzm_registry text COLLATE pg_catalog."default",
    source_info text COLLATE pg_catalog."default",
    lzm_registry_priority integer,
    glpm_method text COLLATE pg_catalog."default",
    lzm_registry_period text COLLATE pg_catalog."default",
    act_num text COLLATE pg_catalog."default",
    modification text COLLATE pg_catalog."default",
    month_new_modified text COLLATE pg_catalog."default",
    registry_insertion_date date,
    locality_comments text COLLATE pg_catalog."default",
    registry_update_date date,
    forest_management_year integer,
    inspection_date date,
    lat numeric,
    lon numeric,
    forestry text COLLATE pg_catalog."default",
    localforestry text COLLATE pg_catalog."default",
    subforestry text COLLATE pg_catalog."default",
    area integer,
    section integer,
    fp_section integer,
    s_section numeric,
    forest_purpose_id integer,
    forest_purpose_tax text COLLATE pg_catalog."default",
    protection_category_id integer,
    ozu_id integer,
    oopt_id integer,
    protection_category_group_id_1olpm integer,
    compound text COLLATE pg_catalog."default",
    age_group_id integer,
    age integer,
    bonitet text COLLATE pg_catalog."default",
    fullness numeric,
    stock_ga integer,
    accessibility text COLLATE pg_catalog."default",
    tenant text COLLATE pg_catalog."default",
    rent_type text COLLATE pg_catalog."default",
    rent_date date,
    rent_validity integer,
    inspection_year integer,
    s_inspection numeric,
    permissive_letter_num text COLLATE pg_catalog."default",
    s_inspection_gis numeric,
    som_id_old integer,
    som_s_old numeric,
    cat_rlh text COLLATE pg_catalog."default",
    main_species text COLLATE pg_catalog."default",
    damaged_species_1olpm text COLLATE pg_catalog."default",
    damage_reason_group_1olpm integer,
    damage_reason text COLLATE pg_catalog."default",
    main_damage_reason_id_1olpm integer,
    secondary_damage_reason_id_1olpm integer,
    damage_year integer,
    protection_category_group_id integer,
    prediction text COLLATE pg_catalog."default",
    damaged_species_2olpm text COLLATE pg_catalog."default",
    damage_reason_group_2olpm integer,
    pests text COLLATE pg_catalog."default",
    main_damage_reason_id_2olpm integer,
    pest_phase text COLLATE pg_catalog."default",
    pest_focus_num text COLLATE pg_catalog."default",
    dead_trees_total_proc numeric,
    drying_degree text COLLATE pg_catalog."default",
    dead_trees_current_proc numeric,
    damaged_trees_proc_2olpm numeric,
    damaged_trees_degree_2olpm text COLLATE pg_catalog."default",
    main_damage_symptom_id_1olpm integer,
    main_damage_symptom_proc_1olpm numeric,
    secondary_damage_symptom_id_1olpm integer,
    secondary_damage_symptom_proc_1olpm numeric,
    rest_fullness numeric,
    undergrowth text COLLATE pg_catalog."default",
    sks_species numeric,
    sks_plantation numeric,
    recommended_mzl_id integer,
    cutting_proc numeric,
    is_dead text COLLATE pg_catalog."default",
    recommended_mzl_s numeric,
    recommended_mzl_stock numeric,
    dead_year integer,
    approved_mzl_id integer,
    approved_mzl_s numeric,
    approved_mzl_stock numeric,
    rad_count integer,
    cat_1 numeric,
    cat_1_cutting numeric,
    cat_2 numeric,
    cat_2_cutting numeric,
    cat_3 numeric,
    cat_3_cutting numeric,
    cat_4 numeric,
    cat_4_cutting numeric,
    cat_5_new_dried numeric,
    cat_5_new_windfall numeric,
    cat_5_new_windbreak numeric,
    cat_5_old_dried numeric,
    cat_5_old_windfall numeric,
    cat_5_old_windbreak numeric,
    s_previous_year numeric,
    s_new_year_01 numeric,
    stock_new_year_01 numeric,
    s_diff_01 numeric,
    s_new_year_02 numeric,
    stock_new_year_02 numeric,
    s_diff_02 numeric,
    s_new_year_03 numeric,
    stock_new_year_03 numeric,
    s_diff_03 numeric,
    s_new_year_04 numeric,
    stock_new_year_04 numeric,
    s_diff_04 numeric,
    s_new_year_05 numeric,
    stock_new_year_05 numeric,
    s_diff_05 numeric,
    s_new_year_06 numeric,
    stock_new_year_06 numeric,
    s_diff_06 numeric,
    s_new_year_07 numeric,
    stock_new_year_07 numeric,
    s_diff_07 numeric,
    s_new_year_08 numeric,
    stock_new_year_08 numeric,
    s_diff_08 numeric,
    s_new_year_09 numeric,
    stock_new_year_09 numeric,
    s_diff_09 numeric,
    s_new_year_10 numeric,
    stock_new_year_10 numeric,
    s_diff_10 numeric,
    s_new_year_11 numeric,
    stock_new_year_11 numeric,
    s_diff_11 numeric,
    s_new_year_12 numeric,
    stock_new_year_12 numeric,
    s_diff_12 numeric,
    total_mzl_id integer,
    total_s_new_year numeric,
    total_stock_new_year numeric,
    lpo_mode text COLLATE pg_catalog."default",
    worker text COLLATE pg_catalog."default",
    "user" text COLLATE pg_catalog."default",
    data_source_1_1 integer,
    comments text COLLATE pg_catalog."default",
    actualization_mode text COLLATE pg_catalog."default"
)